### ISSUE TITLE
Client UX

### ISSUE THREAD

**Issue by harababurel** [googleinterns/e2e-search-ml-probing#8]
I'm running the client without a web interface. This is the output I get:

```
> node client upload-basic
lvTP0KKDJUTFhSa7YUS1 lPTz_9yIQWk
connect ETIMEDOUT 173.194.197.136:443
TypeError: Cannot read property '0' of undefined
    at searchVideoByTitle.then (/home/sergiup/work/e2e-search-ml-probing/client.js:54:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
connect ETIMEDOUT 74.125.143.91:443
TypeError: Cannot read property '0' of undefined
    at searchVideoByTitle.then (/home/sergiup/work/e2e-search-ml-probing/client.js:54:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
connect ETIMEDOUT 74.125.138.91:443
TypeError: Cannot read property '0' of undefined
    at searchVideoByTitle.then (/home/sergiup/work/e2e-search-ml-probing/client.js:54:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
connect ETIMEDOUT 173.194.197.91:443
TypeError: Cannot read property '0' of undefined
    at searchVideoByTitle.then (/home/sergiup/work/e2e-search-ml-probing/client.js:54:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
connect ETIMEDOUT 173.194.222.190:443
TypeError: Cannot read property '0' of undefined
    at searchVideoByTitle.then (/home/sergiup/work/e2e-search-ml-probing/client.js:54:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

1. What do the first 2 strings mean? I suspect one of them is the video id of the newly uploaded video but I have no idea what the other is and other users wouldn't know either. 
2. Should the type error be addressed somewhere in code?
3. What is the client doing at this point? If it didn't output those errors it would be easy to assume that it just hangs doing nothing. As a user, am I waiting for it to output something?

**Comment by 0x5eba** [comment]
This happened to me, basically you run a server while a client was already running. Just stop all your clients and server, and start again, should be fixed

1. Yes, it was for testing, i will remove them
2. the client somehow fail to make the request, so i don't get back a replay with the data, and so i try to read data `Cannot read property '0' of undefined` that is undefined
3. this error should't happen

**Comment by harababurel** [comment]
1. You can keep them as debug-level logging, but make the meaning more explicit (e.g. "Uploaded video successfully. video_id: `lPTz_9yIQWk`"). This way you don't see them by default but you can change the log level if you need to.
2. How do you treat this kind of failure?
3. Even if the error doesn't happen, how does the user know what to do next and what the prober is doing?

**Comment by harababurel** [comment]
Another thing: 

> This happened to me, basically you run a server while a client was already running. Just stop all your clients and server, and start again, should be fixed

How do we eliminate this problem? It's hard to identify the cause and solution of this without knowing the implementation details.

**Comment by 0x5eba** [comment]
2. There is a `then` `catch` in every promise, but that problem is a socket problem, and socket problem don't happen if the server is running in the proper way, so the client shouldn't bother about that. I don't know how to handle them correctly, maybe a try catch in every socket emit, but this won't prevent getting the errors
3. You just wait that all the request are done, if there is a problem a `console.error` display the error, if not, a `console.log` show that everything was fine (I just added this console.log)

> How do we eliminate this problem? It's hard to identify the cause and solution of this without knowing the implementation details.

Simply run stuff in the proper order as expected, is impossible to prevent everything. I guess this is happening because the socket.emit stay in queue until it find the server up, so i can't prevent that
