### ISSUE TITLE
Automation for fresh test accounts.

### ISSUE THREAD

**Issue by harababurel** [googleinterns/e2e-search-ml-probing#9]
When creating a new test account, some manual setup needs to be done:

- create a YouTube channel (requires going through a few steps).
- acknowledge the "Welcome to the new YouTube Studio" popup (breaks the upload flow otherwise).

![image](https://user-images.githubusercontent.com/8619823/86596205-2253af80-bf9a-11ea-8f69-d60ca96e1b4c.png)

It would be useful to have the prober do these steps in order to reduce human intervention.

**Comment by 0x5eba** [comment]
It's hard to test something that appear only once, maybe if you give me like 5 test accounts I will give it a try
